name: olist_analytics
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.11

  # dbt Core and BigQuery
  - pip
  - pip:
    - dbt-core>=1.6.0
    - dbt-bigquery>=1.6.0
    - dbt-utils>=1.1.0

  # Data Processing
  - pandas>=2.0.0
  - numpy>=1.24.0
  - pyarrow>=12.0.0

  # Streamlit Dashboard
  - pip:
    - streamlit>=1.28.0

  # Database Connectivity
  - pip:
    - google-cloud-bigquery>=3.11.0
    - google-auth>=2.22.0
    - google-auth-oauthlib>=1.0.0
    - google-auth-httplib2>=0.1.0
    - db-dtypes>=1.1.0

  # Visualization
  - plotly>=5.15.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - pip:
    - altair>=5.0.0

  # Development Tools
  - jupyter>=1.0.0
  - ipykernel>=6.25.0
  - notebook>=7.0.0

  # Utilities
  - pip:
    - python-dotenv>=1.0.0
    - pydantic>=2.0.0
    - pyyaml>=6.0.0

  # Data Quality & Testing
  - pip:
    - great-expectations>=0.17.0

  # Version Control & Development
  - git>=2.40.0
  - pip:
    - pre-commit>=3.4.0
